version: '3'


services:
    app:
        image: flask_app
        container_name: flask_app
        build: ./app
        volumes:
            - .:/flask_app
        restart: always
        ports:
            - "8000:8000"
